"""empty message

Revision ID: 9aee9c91f9aa
Revises: d883db674f79
Create Date: 2025-03-18 16:11:33.162834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9aee9c91f9aa'
down_revision = 'd883db674f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=250), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('hair_color', sa.String(length=100), nullable=False),
    sa.Column('skin_color', sa.String(length=100), nullable=False),
    sa.Column('eye_color', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('birth_planet', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=250), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('climate', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.Float(), nullable=False),
    sa.Column('rotation_period', sa.Float(), nullable=False),
    sa.Column('orbital_period', sa.Float(), nullable=False),
    sa.Column('terrain', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('lastname', sa.String(length=250), nullable=False),
    sa.Column('suscripcion', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planeta')
    op.drop_table('personaje')
    op.drop_table('usuario')
    op.drop_table('favorito')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], name='favorito_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], name='favorito_planeta_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='favorito_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_pkey')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('suscripcion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('estado_activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey'),
    sa.UniqueConstraint('email', name='usuario_email_key')
    )
    op.create_table('personaje',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_personaje', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('altura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('color_pelo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color_piel', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color_ojos', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fecha_nacimiento', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('genero', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('especie', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('planeta_natal', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='personaje_pkey')
    )
    op.create_table('planeta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_planeta', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('diametro', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('clima', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('poblacion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gravedad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('periodo_rotacion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('periodo_orbital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('terreno', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planeta_pkey')
    )
    op.drop_table('favorite')
    op.drop_table('user')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
